### ISSUE TITLE
Task: Review urban_gov_ai article

### ISSUE THREAD

**Issue by myriamgui** [CUPUM/urban-gov-ai#3]
# Task Description
Review latest version of urban_gov_ai literature review article written by @myriamgui, found [here](https://cirrus.gnp.umontreal.ca/index.php/s/PjYeGDHMyMJWTTP).

# List of actions
- [x] Action: Review article
- [x] Action: Incorporate comments and inputs

**Comment by sjinko** [comment]
J’ai ajouté des commentaires / suggestions dans l’intro. Le document [édité est sur Cirrus](https://cirrus.gnp.umontreal.ca/index.php/f/416982)

**Comment by sjinko** [comment]
Quick question: Dans la revue de la littérature scientifique, je trouve des références à des articles qui ne concernent pas l’IA. Par exemple Langley and Leyshon, 2017. Est-ce normal?

**Comment by myriamgui** [comment]
L'idée des plateformes dont font mention Langley et Leyshon sont basées sur du Machine Learning et l'algorithme de regression, j'ai donc inclus le texte dans la recension finale

**Comment by sjinko** [comment]
J’ai fait une recherche rapide par mots clés, et je ne trouve pas de référence au ML dans le texte. Peux-tu me dire comment tu as identifié que les plateformes sont basées sur le ML?

**Comment by myriamgui** [comment]
Shaw (2020) mentionne un peu les algorithmes utilisés. J'ai également regardé le type de plateforme dont il est question comme Zillow ou des trucs plus récents comme Ireal.ai qui se définissent eux-mêmes comme mobilisant le machine learning

**Comment by sjinko** [comment]
Ok, super, merci. Ça m’est très utile!

Shin Koseki
Titulaire de la Chaire UNESCO en paysage urbain /
  UNESCO Chair Professor in Urban Landscape
Université de Montréal
________________________________
